package ebank.business.validation;

/**
 * Concrete strategy: the captcha entered by the user must match
 * the captcha generated by the system for the current login attempt.
 */
public class CaptchaValidator implements Validator {

    private final String generatedCaptcha;

    public CaptchaValidator(String generatedCaptcha) {
        this.generatedCaptcha = generatedCaptcha;
    }

    @Override
    public boolean validate(String input) {
        return input != null && input.equals(generatedCaptcha);
    }

    @Override
    public String getValidKey() {
        return "captcha.valid";
    }

    @Override
    public String getErrorKey() {
        return "captcha.invalid";
    }
}
